version: '3.8'

services:
  discord-automod-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: automod-bot
    restart: unless-stopped
    
    # Variables de entorno
    environment:
      - NODE_ENV=production
      - TZ=UTC
    
    # Archivo de variables de entorno
    env_file:
      - .env
    
    # Volúmenes para persistir datos
    volumes:
      - ./database.json:/usr/src/app/database.json:rw
      - ./logs:/usr/src/app/logs:rw
    
    # Configuración de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Política de reinicio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Servicio de monitoreo con Watchtower
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30 --cleanup
  #   restart: unless-stopped